AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ScrapyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "ScrapyMint"
      Handler: src/lambda_function.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          GOOGLE_APPLICATION_CREDENTIALS: "/var/task/src/service_account.json"
      Policies:
        - AWSLambdaBasicExecutionRole
