AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ScrapyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          GOOGLE_APPLICATION_CREDENTIALS: "/var/task/service_account.json"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Events:
        GitHubTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)