name: Deploy to AWS Lambda

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  

    - name: Crear archivo service_account.json
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > src/service_account.json

    - name: Configurar variables de entorno adicionales
      run: |
        echo "GOOGLE_DRIVE_FOLDER_PDF_ID=${{ secrets.GOOGLE_DRIVE_FOLDER_PDF_ID }}" >> $GITHUB_ENV
        echo "GOOGLE_DRIVE_FOLDER_CSV_ID=${{ secrets.GOOGLE_DRIVE_FOLDER_CSV_ID }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build and Deploy with AWS SAM
      run: |
        sam build
        sam deploy --no-confirm-changeset --stack-name ScrapyLambdaStack --capabilities CAPABILITY_NAMED_IAM \
          --s3-bucket nombre-del-bucket \
          --parameter-overrides \
          GoogleDriveFolderPdfId=${{ secrets.GOOGLE_DRIVE_FOLDER_PDF_ID }} \
          GoogleDriveFolderCsvId=${{ secrets.GOOGLE_DRIVE_FOLDER_CSV_ID }}
